export const USERS_SET = 'USERS_SET';

export const USER_SET = 'USER_SET';

export const USER_REMOVE = 'USER_REMOVE';

export const ROLES_SET = 'ROLES_SET';

export const PRODUCTS_SET = 'PRODUCTS_SET';

export const PRODUCT_SET = 'PRODUCT_SET';

export const PRODUCT_REMOVE = 'PRODUCT_REMOVE';

export const CATEGORIES_SET = 'CATEGORIES_SET';

export const PRODUCTDETAILS_SET = 'PRODUCTDETAILS_SET';

export const PRODUCTDETAIL_SET = 'PRODUCTDETAIL_SET';

export const PRODUCTDETAIL_REMOVE = 'PRODUCTDETAIL_REMOVE';
